# Generated by Django 4.1.7 on 2023-03-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0010_producttoshoppingcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shops',
            field=models.ManyToManyField(through='shopapp.ProductToShop', to='shopapp.shop'),
        ),
    ]
