# Generated by Django 4.1.7 on 2023-03-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0011_product_shops'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shopping_cart',
            field=models.ManyToManyField(through='shopapp.ProductToShoppingCart', to='shopapp.shoppingcart'),
        ),
    ]
