# Generated by Django 4.1.7 on 2023-03-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0012_product_shopping_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='orders',
            field=models.ManyToManyField(through='shopapp.ProductToOrder', to='shopapp.order'),
        ),
    ]
