# Generated by Django 4.1.7 on 2023-03-09 12:23

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0013_product_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20)),
                ('discount_coefficient', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('0.99'))])),
                ('name_of_func_to_check', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='shopping_cart',
            field=models.ManyToManyField(related_name='products', through='shopapp.ProductToShoppingCart', to='shopapp.shoppingcart'),
        ),
    ]
