# Generated by Django 4.1.7 on 2023-03-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0014_stocks_alter_product_shopping_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
