# Generated by Django 4.1.7 on 2023-03-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='purchase_amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
